/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package expresionesr;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;

/**
 *
 * @author kenit
 */
public class Menu extends javax.swing.JFrame
{

    int typeOf = 1;
    ImageIcon tk = new ImageIcon(getClass().getResource("/img/tick.png"));
    ImageIcon css = new ImageIcon(getClass().getResource("/img/cross.png"));

    /**
     * Creates new form Menu
     */
    public Menu()
    {
        initComponents();
        setLocationRelativeTo(null);
        jRCURP.setSelected(true);
        CorrectorNo.setText(null);
    }

    public boolean validaCURP(String ev)
    {
        Pattern pat = Pattern.compile("[A-Z]{1}[AEIOU]{1}[A-Z]{2}[0-9]{2}"
                + "(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])"
                + "[HM]{1}"
                + "(AS|BC|BS|CC|CS|CH|CL|CM|DF|DG|GT|GR|HG|JC|MC|MN|MS|NT|NL|OC|PL|QT|QR|SP|SL|SR|TC|TS|TL|VZ|YN|ZS|NE)"
                + "[B-DF-HJ-NP-TV-Z]{3}"
                + "[0-9A-Z]{1}[0-9]{1}$");
        Matcher matcher = pat.matcher(ev);
        if (matcher.find())
        {
            CorrectorNo.setIcon(tk);
        } else
        {
            CorrectorNo.setIcon(css);
        }
        return matcher.find();
    }

    public boolean validaCE(String ev)
    {
        Pattern pat = Pattern.compile("^([0-9a-zA-Z]+[-._+&])*[0-9a-zA-Z]+@([-0-9a-zA-Z]+[.])+[a-zA-Z]{2,6}$");
        Matcher matcher = pat.matcher(ev);
        if (matcher.find())
        {
            CorrectorNo.setIcon(tk);
        } else
        {
            CorrectorNo.setIcon(css);
        }
        return matcher.find();
    }

    public boolean validaRFC(String ev)
    {
        Pattern pat = Pattern.compile("^([A-ZÑ\\x26]{3,4}([0-9]{2})(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])([A-Z]|[0-9]){2}([A]|[0-9]){1})?$");
        Matcher matcher = pat.matcher(ev);
        if (matcher.find())
        {
            CorrectorNo.setIcon(tk);
        } else
        {
            CorrectorNo.setIcon(css);
        }
        return matcher.find();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLIngrese = new javax.swing.JLabel();
        jTEvaluador = new javax.swing.JTextField();
        CorrectorNo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jRRFC = new javax.swing.JRadioButton();
        jRCorreoE = new javax.swing.JRadioButton();
        jRCURP = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setText("Evaluador de expresiones regulares");

        jLIngrese.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        jLIngrese.setText("Ingrese su CURP: ");

        jTEvaluador.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        jTEvaluador.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                jTEvaluadorKeyReleased(evt);
            }
        });

        buttonGroup1.add(jRRFC);
        jRRFC.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        jRRFC.setText("RFC");
        jRRFC.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRRFCActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRCorreoE);
        jRCorreoE.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        jRCorreoE.setText("Correo electronico");
        jRCorreoE.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRCorreoEActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRCURP);
        jRCURP.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        jRCURP.setText("CURP");
        jRCURP.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRCURPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRCURP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(jRCorreoE)
                .addGap(117, 117, 117)
                .addComponent(jRRFC)
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRRFC)
                    .addComponent(jRCorreoE)
                    .addComponent(jRCURP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLIngrese)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTEvaluador, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CorrectorNo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLIngrese)
                            .addComponent(jTEvaluador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(CorrectorNo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTEvaluadorKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTEvaluadorKeyReleased
    {//GEN-HEADEREND:event_jTEvaluadorKeyReleased

        if (!jTEvaluador.getText().isEmpty())
        {
            if (typeOf == 1)
            {
                //System.out.println("Evaluanddo CURP");
                validaCURP(jTEvaluador.getText());
            }
            if (typeOf == 2)
            {
                //System.out.println("Evaluando Correo Electronico");
                validaCE(jTEvaluador.getText());
            }
            if (typeOf == 3)
            {
                //System.out.println("Evaluando RFC");
                validaRFC(jTEvaluador.getText());
            }
        }else
        {
            CorrectorNo.setIcon(null);
        }

    }//GEN-LAST:event_jTEvaluadorKeyReleased

    private void jRCURPActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRCURPActionPerformed
    {//GEN-HEADEREND:event_jRCURPActionPerformed
        typeOf = 1;
        jLIngrese.setText("Ingrese su CURP");
        jTEvaluador.setText(null);
    }//GEN-LAST:event_jRCURPActionPerformed

    private void jRCorreoEActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRCorreoEActionPerformed
    {//GEN-HEADEREND:event_jRCorreoEActionPerformed
        typeOf = 2;
        jLIngrese.setText("Ingrese su Correo Electronico");
        jTEvaluador.setText(null);
    }//GEN-LAST:event_jRCorreoEActionPerformed

    private void jRRFCActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRRFCActionPerformed
    {//GEN-HEADEREND:event_jRRFCActionPerformed
        typeOf = 3;
        jLIngrese.setText("Ingrese su RFC");
        jTEvaluador.setText(null);
    }//GEN-LAST:event_jRRFCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CorrectorNo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLIngrese;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRCURP;
    private javax.swing.JRadioButton jRCorreoE;
    private javax.swing.JRadioButton jRRFC;
    private javax.swing.JTextField jTEvaluador;
    // End of variables declaration//GEN-END:variables
}
